
(function(){var dhgate,callback=jQuery.Callbacks('once'),jobs={};var regNs=function(ns,fn){var nslist=ns.split('.'),step=dhgate,k=null;while(k=nslist.shift()){if(nslist.length){if(step[k]===undefined){step[k]={};}
step=step[k];}else{if(step[k]===undefined){return step[k]=fn.call(window,jQuery,dhgate);}}}};var regJob=function(ns,fn){if(jobs[ns]){throw new Error(ns+' has exist!');}else{jobs[ns]=fn;}
callback.add(fn);};var startJob=function(ns){if(ns){jobs[ns]&&jobs[ns].call(dhgate,dhgate);}else{callback.fire(dhgate);}};dhgate={regNs:regNs,regJob:regJob,startJob:startJob};this.D=dhgate;}).call(window);D.regNs('core.base.spine',function(){var $,Controller,Events,Log,Model,Module,Spine,createObject,isArray,isBlank,makeArray,moduleKeywords,__slice=[].slice,__indexOf=[].indexOf||function(item){for(var i=0,l=this.length;i<l;i++){if(i in this&&this[i]===item)
return i;}
return-1;},__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))
child[key]=parent[key];}
function ctor(){this.constructor=child;}
ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;},__bind=function(fn,me){return function(){return fn.apply(me,arguments);};};Events={bind:function(ev,callback){var calls,evs,name,_i,_len;evs=ev.split(' ');calls=this.hasOwnProperty('_callbacks')&&this._callbacks||(this._callbacks={});for(_i=0,_len=evs.length;_i<_len;_i++){name=evs[_i];calls[name]||(calls[name]=[]);calls[name].push(callback);}
return this;},one:function(ev,callback){return this.bind(ev,function(){this.unbind(ev,arguments.callee);return callback.apply(this,arguments);});},trigger:function(){var args,callback,ev,list,_i,_len,_ref;args=1<=arguments.length?__slice.call(arguments,0):[];ev=args.shift();list=this.hasOwnProperty('_callbacks')&&((_ref=this._callbacks)!=null?_ref[ev]:void 0);if(!list){return;}
for(_i=0,_len=list.length;_i<_len;_i++){callback=list[_i];if(callback.apply(this,args)===false){break;}}
return true;},unbind:function(ev,callback){var cb,i,list,_i,_len,_ref;if(!ev){this._callbacks={};return this;}
list=(_ref=this._callbacks)!=null?_ref[ev]:void 0;if(!list){return this;}
if(!callback){delete this._callbacks[ev];return this;}
for(i=_i=0,_len=list.length;_i<_len;i=++_i){cb=list[i];if(!(cb===callback)){continue;}
list=list.slice();list.splice(i,1);this._callbacks[ev]=list;break;}
return this;}};Log={trace:true,logPrefix:'(App)',log:function(){var args;args=1<=arguments.length?__slice.call(arguments,0):[];if(!this.trace){return;}
if(this.logPrefix){args.unshift(this.logPrefix);}
if(typeof console!=="undefined"&&console!==null){if(typeof console.log==="function"){console.log.apply(console,args);}}
return this;}};moduleKeywords=['included','extended'];Module=(function(){Module.include=function(obj){var key,value,_ref;if(!obj){throw new Error('include(obj) requires obj');}
for(key in obj){value=obj[key];if(__indexOf.call(moduleKeywords,key)<0){this.prototype[key]=value;}}
if((_ref=obj.included)!=null){_ref.apply(this);}
return this;};Module.extend=function(obj){var key,value,_ref;if(!obj){throw new Error('extend(obj) requires obj');}
for(key in obj){value=obj[key];if(__indexOf.call(moduleKeywords,key)<0){this[key]=value;}}
if((_ref=obj.extended)!=null){_ref.apply(this);}
return this;};Module.proxy=function(func){var _this=this;return function(){return func.apply(_this,arguments);};};Module.prototype.proxy=function(func){var _this=this;return function(){return func.apply(_this,arguments);};};function Module(){if(typeof this.init==="function"){this.init.apply(this,arguments);}}
return Module;})();Model=(function(_super){__extends(Model,_super);Model.extend(Events);Model.records={};Model.crecords={};Model.attributes=[];Model.configure=function(){var attributes,name;name=arguments[0],attributes=2<=arguments.length?__slice.call(arguments,1):[];this.className=name;this.records={};this.crecords={};if(attributes.length){this.attributes=attributes;}
this.attributes&&(this.attributes=makeArray(this.attributes));this.attributes||(this.attributes=[]);this.unbind();return this;};Model.toString=function(){return""+this.className+"("+(this.attributes.join(", "))+")";};Model.find=function(id){var record;record=this.records[id];if(!record&&(""+id).match(/c-\d+/)){return this.findCID(id);}
if(!record){throw new Error('Unknown record');}
return record.clone();};Model.findCID=function(cid){var record;record=this.crecords[cid];if(!record){throw new Error('Unknown record');}
return record.clone();};Model.exists=function(id){try{return this.find(id);}
catch(e){return false;}};Model.refresh=function(values,options){var record,records,_i,_len;if(options==null){options={};}
if(options.clear){this.records={};this.crecords={};}
records=this.fromJSON(values);if(!isArray(records)){records=[records];}
for(_i=0,_len=records.length;_i<_len;_i++){record=records[_i];record.id||(record.id=record.cid);this.records[record.id]=record;this.crecords[record.cid]=record;}
this.trigger('refresh',this.cloneArray(records));return this;};Model.select=function(callback){var id,record,result;result=(function(){var _ref,_results;_ref=this.records;_results=[];for(id in _ref){record=_ref[id];if(callback(record)){_results.push(record);}}
return _results;}).call(this);return this.cloneArray(result);};Model.findByAttribute=function(name,value){var id,record,_ref;_ref=this.records;for(id in _ref){record=_ref[id];if(record[name]===value){return record.clone();}}
return null;};Model.findAllByAttribute=function(name,value){return this.select(function(item){return item[name]===value;});};Model.each=function(callback){var key,value,_ref,_results;_ref=this.records;_results=[];for(key in _ref){value=_ref[key];_results.push(callback(value.clone()));}
return _results;};Model.all=function(){return this.cloneArray(this.recordsValues());};Model.first=function(){var record;record=this.recordsValues()[0];return record!=null?record.clone():void 0;};Model.last=function(){var record,values;values=this.recordsValues();record=values[values.length-1];return record!=null?record.clone():void 0;};Model.count=function(){return this.recordsValues().length;};Model.deleteAll=function(){var key,value,_ref,_results;_ref=this.records;_results=[];for(key in _ref){value=_ref[key];_results.push(delete this.records[key]);}
return _results;};Model.destroyAll=function(){var key,value,_ref,_results;_ref=this.records;_results=[];for(key in _ref){value=_ref[key];_results.push(this.records[key].destroy());}
return _results;};Model.update=function(id,atts,options){return this.find(id).updateAttributes(atts,options);};Model.create=function(atts,options){var record;record=new this(atts);return record.save(options);};Model.destroy=function(id,options){return this.find(id).destroy(options);};Model.change=function(callbackOrParams){if(typeof callbackOrParams==='function'){return this.bind('change',callbackOrParams);}
else{return this.trigger('change',callbackOrParams);}};Model.fetch=function(callbackOrParams){if(typeof callbackOrParams==='function'){return this.bind('fetch',callbackOrParams);}
else{return this.trigger('fetch',callbackOrParams);}};Model.toJSON=function(){return this.recordsValues();};Model.fromJSON=function(objects){var value,_i,_len,_results;if(!objects){return;}
if(typeof objects==='string'){objects=JSON.parse(objects);}
if(isArray(objects)){_results=[];for(_i=0,_len=objects.length;_i<_len;_i++){value=objects[_i];_results.push(new this(value));}
return _results;}
else{return new this(objects);}};Model.fromForm=function(){var _ref;return(_ref=new this).fromForm.apply(_ref,arguments);};Model.recordsValues=function(){var key,result,value,_ref;result=[];_ref=this.records;for(key in _ref){value=_ref[key];result.push(value);}
return result;};Model.cloneArray=function(array){var value,_i,_len,_results;_results=[];for(_i=0,_len=array.length;_i<_len;_i++){value=array[_i];_results.push(value.clone());}
return _results;};Model.idCounter=0;Model.uid=function(prefix){var uid;if(prefix==null){prefix='';}
uid=prefix+this.idCounter++;if(this.exists(uid)){uid=this.uid(prefix);}
return uid;};function Model(atts){Model.__super__.constructor.apply(this,arguments);if(atts){this.load(atts);}
this.cid=this.constructor.uid('c-');}
Model.prototype.isNew=function(){return!this.exists();};Model.prototype.isValid=function(){return!this.validate();};Model.prototype.validate=function(){};Model.prototype.load=function(atts){var key,value;for(key in atts){value=atts[key];if(typeof this[key]==='function'){this[key](value);}
else{this[key]=value;}}
return this;};Model.prototype.attributes=function(){var key,result,_i,_len,_ref;result={};_ref=this.constructor.attributes;for(_i=0,_len=_ref.length;_i<_len;_i++){key=_ref[_i];if(key in this){if(typeof this[key]==='function'){result[key]=this[key]();}
else{result[key]=this[key];}}}
if(this.id){result.id=this.id;}
return result;};Model.prototype.eql=function(rec){return!!(rec&&rec.constructor===this.constructor&&(rec.cid===this.cid)||(rec.id&&rec.id===this.id));};Model.prototype.save=function(options){var error,record;if(options==null){options={};}
if(options.validate!==false){error=this.validate();if(error){this.trigger('error',error);return false;}}
this.trigger('beforeSave',options);record=this.isNew()?this.create(options):this.update(options);this.trigger('save',options);return record;};Model.prototype.updateAttribute=function(name,value,options){this[name]=value;return this.save(options);};Model.prototype.updateAttributes=function(atts,options){this.load(atts);return this.save(options);};Model.prototype.changeID=function(id){var records;records=this.constructor.records;records[id]=records[this.id];delete records[this.id];this.id=id;return this.save();};Model.prototype.destroy=function(options){if(options==null){options={};}
this.trigger('beforeDestroy',options);delete this.constructor.records[this.id];delete this.constructor.crecords[this.cid];this.destroyed=true;this.trigger('destroy',options);this.trigger('change','destroy',options);this.unbind();return this;};Model.prototype.dup=function(newRecord){var result;result=new this.constructor(this.attributes());if(newRecord===false){result.cid=this.cid;}
else{delete result.id;}
return result;};Model.prototype.clone=function(){return createObject(this);};Model.prototype.reload=function(){var original;if(this.isNew()){return this;}
original=this.constructor.find(this.id);this.load(original.attributes());return original;};Model.prototype.toJSON=function(){return this.attributes();};Model.prototype.toString=function(){return"<"+this.constructor.className+" ("+(JSON.stringify(this))+")>";};Model.prototype.fromForm=function(form){var key,result,_i,_len,_ref;result={};_ref=$(form).serializeArray();for(_i=0,_len=_ref.length;_i<_len;_i++){key=_ref[_i];result[key.name]=key.value;}
return this.load(result);};Model.prototype.exists=function(){return this.id&&this.id in this.constructor.records;};Model.prototype.update=function(options){var clone,records;this.trigger('beforeUpdate',options);records=this.constructor.records;records[this.id].load(this.attributes());clone=records[this.id].clone();clone.trigger('update',options);clone.trigger('change','update',options);return clone;};Model.prototype.create=function(options){var clone,record;this.trigger('beforeCreate',options);if(!this.id){this.id=this.cid;}
record=this.dup(false);this.constructor.records[this.id]=record;this.constructor.crecords[this.cid]=record;clone=record.clone();clone.trigger('create',options);clone.trigger('change','create',options);return clone;};Model.prototype.bind=function(events,callback){var binder,unbinder,_this=this;this.constructor.bind(events,binder=function(record){if(record&&_this.eql(record)){return callback.apply(_this,arguments);}});this.constructor.bind('unbind',unbinder=function(record){if(record&&_this.eql(record)){_this.constructor.unbind(events,binder);return _this.constructor.unbind('unbind',unbinder);}});return binder;};Model.prototype.one=function(events,callback){var binder,_this=this;return binder=this.bind(events,function(){_this.constructor.unbind(events,binder);return callback.apply(_this,arguments);});};Model.prototype.trigger=function(){var args,_ref;args=1<=arguments.length?__slice.call(arguments,0):[];args.splice(1,0,this);return(_ref=this.constructor).trigger.apply(_ref,args);};Model.prototype.unbind=function(){return this.trigger('unbind');};return Model;})(Module);Controller=(function(_super){__extends(Controller,_super);Controller.include(Events);Controller.include(Log);Controller.prototype.eventSplitter=/^(\S+)\s*(.*)$/;Controller.prototype.tag='div';function Controller(options){this.release=__bind(this.release,this);var key,value,_ref;this.options=options;_ref=this.options;for(key in _ref){value=_ref[key];this[key]=value;}
if(!this.el){this.el=document.createElement(this.tag);}
this.el=$(this.el);this.$el=this.el;if(this.className){this.el.addClass(this.className);}
if(this.attributes){this.el.attr(this.attributes);}
if(!this.events){this.events=this.constructor.events;}
if(!this.elements){this.elements=this.constructor.elements;}
if(this.events){this.delegateEvents(this.events);}
if(this.elements){this.refreshElements();}
Controller.__super__.constructor.apply(this,arguments);}
Controller.prototype.release=function(){this.trigger('release');this.el.remove();return this.unbind();};Controller.prototype.$=function(selector){return $(selector,this.el);};Controller.prototype.delegateEvents=function(events){var eventName,key,match,method,selector,_results,_this=this;_results=[];for(key in events){method=events[key];if(typeof method==='function'){method=(function(method){return function(){method.apply(_this,arguments);return true;};})(method);}
else{if(!this[method]){throw new Error(""+method+" doesn't exist");}
method=(function(method){return function(){_this[method].apply(_this,arguments);return true;};})(method);}
match=key.match(this.eventSplitter);eventName=match[1];selector=match[2];if(selector===''){_results.push(this.el.bind(eventName,method));}
else{_results.push(this.el.delegate(selector,eventName,method));}}
return _results;};Controller.prototype.refreshElements=function(){var key,value,_ref,_results;_ref=this.elements;_results=[];for(key in _ref){value=_ref[key];_results.push(this[value]=this.$(key));}
return _results;};Controller.prototype.delay=function(func,timeout){return setTimeout(this.proxy(func),timeout||0);};Controller.prototype.html=function(element){this.el.html(element.el||element);this.refreshElements();return this.el;};Controller.prototype.append=function(){var e,elements,_ref;elements=1<=arguments.length?__slice.call(arguments,0):[];elements=(function(){var _i,_len,_results;_results=[];for(_i=0,_len=elements.length;_i<_len;_i++){e=elements[_i];_results.push(e.el||e);}
return _results;})();(_ref=this.el).append.apply(_ref,elements);this.refreshElements();return this.el;};Controller.prototype.appendTo=function(element){this.el.appendTo(element.el||element);this.refreshElements();return this.el;};Controller.prototype.prepend=function(){var e,elements,_ref;elements=1<=arguments.length?__slice.call(arguments,0):[];elements=(function(){var _i,_len,_results;_results=[];for(_i=0,_len=elements.length;_i<_len;_i++){e=elements[_i];_results.push(e.el||e);}
return _results;})();(_ref=this.el).prepend.apply(_ref,elements);this.refreshElements();return this.el;};Controller.prototype.replace=function(element){var previous,_ref;_ref=[this.el,$(element.el||element)],previous=_ref[0],this.el=_ref[1];previous.replaceWith(this.el);this.delegateEvents(this.events);this.refreshElements();return this.el;};return Controller;})(Module);$=(typeof window!=="undefined"&&window!==null?window.jQuery:void 0)||(typeof window!=="undefined"&&window!==null?window.Zepto:void 0)||function(element){return element;};createObject=Object.create||function(o){var Func;Func=function(){};Func.prototype=o;return new Func();};isArray=function(value){return Object.prototype.toString.call(value)==='[object Array]';};isBlank=function(value){var key;if(!value){return true;}
for(key in value){return false;}
return true;};makeArray=function(args){return Array.prototype.slice.call(args,0);};Spine=this.Spine={};if(typeof module!=="undefined"&&module!==null){module.exports=Spine;}
Spine.version='1.0.8';Spine.isArray=isArray;Spine.isBlank=isBlank;Spine.$=$;Spine.Events=Events;Spine.Log=Log;Spine.Module=Module;Spine.Controller=Controller;Spine.Model=Model;Module.extend.call(Spine,Events);Module.create=Module.sub=Controller.create=Controller.sub=Model.sub=function(instances,statics){var result;result=(function(_super){__extends(result,_super);function result(){return result.__super__.constructor.apply(this,arguments);}
return result;})(this);if(instances){result.include(instances);}
if(statics){result.extend(statics);}
if(typeof result.unbind==="function"){result.unbind();}
return result;};Model.setup=function(name,attributes){var Instance;if(attributes==null){attributes=[];}
Instance=(function(_super){__extends(Instance,_super);function Instance(){return Instance.__super__.constructor.apply(this,arguments);}
return Instance;})(this);Instance.configure.apply(Instance,[name].concat(__slice.call(attributes)));return Instance;};Spine.Class=Module;return Spine;});D.regNs('core.util.observer',function($){var o=$({});return{subscribe:function(){o.on.apply(o,arguments);},unsubscribe:function(){o.off.apply(o,arguments);},publish:function(){o.trigger.apply(o,arguments);}};});D.regNs('core.util.easyTemplate',function(){var easyTemplate=function(s,d){if(!s){return'';}
if(s!==easyTemplate.template){easyTemplate.template=s;easyTemplate.aStatement=easyTemplate.parsing(easyTemplate.separate(s));}
var aST=easyTemplate.aStatement;var process=function(d2){if(d2){d=d2;}
return arguments.callee;};process.toString=function(){return(new Function(aST[0],aST[1]))(d);};return process;};easyTemplate.separate=function(s){var r=/\\'/g;var sRet=s.replace(/(<(\/?)#(.*?(?:\(.*?\))*)>)|(')|([\r\n\t])|(\$\{([^\}]*?)\})/g,function(a,b,c,d,e,f,g,h){if(b){return'{|}'+(c?'-':'+')+d+'{|}';}
if(e){return'\\\'';}
if(f){return'';}
if(g){return'\'+('+h.replace(r,'\'')+')+\'';}});return sRet;};easyTemplate.parsing=function(s){var mName,vName,sTmp,aTmp,sFL,sEl,aList,aStm=['var aRet = [];'];aList=s.split(/\{\|\}/);var r=/\s/;while(aList.length){sTmp=aList.shift();if(!sTmp){continue;}
sFL=sTmp.charAt(0);if(sFL!=='+'&&sFL!=='-'){sTmp='\''+sTmp+'\'';aStm.push('aRet.push('+sTmp+');');continue;}
aTmp=sTmp.split(r);switch(aTmp[0]){case'+macro':mName=aTmp[1];vName=aTmp[2];aStm.push('aRet.push("<!--'+mName+' start--\>");');break;case'-macro':aStm.push('aRet.push("<!--'+mName+' end--\>");');break;case'+if':aTmp.splice(0,1);aStm.push('if'+aTmp.join(' ')+'{');break;case'+elseif':aTmp.splice(0,1);aStm.push('}else if'+aTmp.join(' ')+'{');break;case'-if':aStm.push('}');break;case'+else':aStm.push('}else{');break;case'+list':aStm.push('if('+aTmp[1]+'&&'+aTmp[1]+'.constructor === Array){with({i:0,l:'+aTmp[1]+'.length,'+aTmp[3]+'_index:0,'+aTmp[3]+':null}){for(i=l;i--;){'+aTmp[3]+'_index=(l-i-1);'+aTmp[3]+'='+aTmp[1]+'['+aTmp[3]+'_index];');break;case'-list':aStm.push('}}}');break;default:break;}}
aStm.push('return aRet.join("");');if(!vName){aStm.unshift('var data = arguments[0];');}
return[vName,aStm.join('')];};return easyTemplate;});D.regNs('core.ui.autocomplete',function($,D){return function(el,opts){var $el=$(el),_opts={url:'/',minLength:1,maxLength:100,delay:800,appendTo:$(document.body),name:'q',param:{},tpl:'<#tpl data>\
       <ul>\
       <#list data as val>\
        <li data-val="${val.replace(/<[^>]+>/ig,"")}">${val}</li>\
       </#list>\
       </ul>\
      </#tpl>',selectCls:'on'};if(opts){$.extend(_opts,opts);}
var cache={},append=$(_opts.appendTo),xhr=null,index=-1,childs=[],itv=0,$tmpl=D.core.util.easyTemplate,selectCls=_opts.selectCls,$observer=D.core.util.observer;$el.on('input',function(){var val=$.trim($el.val());if(val.length>=_opts.minLength&&val.length<=_opts.maxLength){clearTimeout(itv);var result=cache[val];if(!result){xhr&&xhr.abort&&xhr.abort();itv=setTimeout(function(){var param={};param[_opts.name]=val;xhr=$.get(_opts.url,$.extend(_opts.param,param),function(result){if(result.length){var resultArr=$.map(result.split('|'),function(str){str=$.trim(str);if(str.length){return str;}});$el.trigger('render.autocomplete',[cache[val]=resultArr]);}})},_opts.delay);}else{$el.trigger('render.autocomplete',[result]);}}else{$el.trigger('render.autocomplete',[]);}}).on('render.autocomplete',function(evt,result){if(result&&result.length){var html=$tmpl(_opts.tpl,result).toString();append.html(html).show();}else{append.hide();}
childs=$('li',append);index=-1;}).on('propertychange',function(evt){var $this=$(this);if(evt.originalEvent.propertyName=='value'){if($this.data('reason')){$this.removeData('reason');}else{$this.trigger('input');}}}).on('keydown',function(evt){if(childs.length){switch(evt.keyCode){case 38:if(--index<0){index=childs.length-1;}
break;case 40:if(++index>childs.length-1){index=0;}
break;default:return;}
var current=childs.eq(index);current.trigger('select.autocomplete');}});append.on('mouseenter.autocomplete','li',function(evt){var target=$(evt.currentTarget);index=target.index();target.addClass(selectCls).siblings('.'+selectCls).removeClass(selectCls);}).on('select.autocomplete','li',function(evt){var item=$(evt.currentTarget),val=item.attr('data-val');if(val.length){$el.val(val);}
$(this).trigger('mouseenter.autocomplete',item);}).on('click','li',function(evt){var target=$(evt.currentTarget),val=target.attr('data-val');if(val.length){$el.data('reason',1).val(val);};append.hide();$observer.publish('submit.autocomplete',[val]);return false;});$observer.subscribe('hide.autocomplete',function(){append.hide();});$(document.body).on('click.autocomplete',function(evt){var target=evt.target;if(append.is(':visible')&&!$.contains(append[0],target)&&$el[0]!==target){append.hide();}});}});D.regNs('core.base.ajax',function(){var $,Ajax,Base,Collection,Extend,Include,Model,Queue,Singleton,Spine,__bind=function(fn,me){return function(){return fn.apply(me,arguments);};},__hasProp={}.hasOwnProperty,__extends=function(child,parent){for(var key in parent){if(__hasProp.call(parent,key))
child[key]=parent[key];}
function ctor(){this.constructor=child;}
ctor.prototype=parent.prototype;child.prototype=new ctor();child.__super__=parent.prototype;return child;},__slice=[].slice;Spine=this.Spine||require('spine');$=Spine.$;Model=Spine.Model;Queue=$({});Ajax={getURL:function(object){return object&&(typeof object.url==="function"?object.url():void 0)||object.url;},enabled:true,disable:function(callback){if(this.enabled){this.enabled=false;try{return callback();}
catch(e){throw e;}
finally{this.enabled=true;}}
else{return callback();}},queue:function(request){if(request){return Queue.queue(request);}
else{return Queue.queue();}},clearQueue:function(){return this.queue([]);}};Base=(function(){function Base(){}
Base.prototype.defaults={contentType:'application/json',dataType:'json',processData:false,headers:{'X-Requested-With':'XMLHttpRequest'}};Base.prototype.queue=Ajax.queue;Base.prototype.ajax=function(params,defaults){return $.ajax(this.ajaxSettings(params,defaults));};Base.prototype.ajaxQueue=function(params,defaults){var deferred,jqXHR,promise,request,settings;jqXHR=null;deferred=$.Deferred();promise=deferred.promise();if(!Ajax.enabled){return promise;}
settings=this.ajaxSettings(params,defaults);request=function(next){jqXHR=$.ajax(settings);jqXHR.done(deferred.resolve).fail(deferred.reject).then(next,next);return jqXHR};promise.abort=function(statusText){var index;if(jqXHR){return jqXHR.abort(statusText);}
index=$.inArray(request,this.queue());if(index>-1){this.queue().splice(index,1);}
deferred.rejectWith(settings.context||settings,[promise,statusText,'']);return promise;};this.queue(request);return promise;};Base.prototype.ajaxSettings=function(params,defaults){return $.extend({},this.defaults,defaults,params);};return Base;})();Collection=(function(_super){__extends(Collection,_super);function Collection(model){this.model=model;this.failResponse=__bind(this.failResponse,this);this.recordsResponse=__bind(this.recordsResponse,this);};Collection.prototype.find=function(id,params){var record;record=new this.model({id:id});return this.ajaxQueue(params,{type:'GET',url:Ajax.getURL(record)}).done(this.recordsResponse).fail(this.failResponse);};Collection.prototype.all=function(params){return this.ajaxQueue(params,{type:'GET',url:Ajax.getURL(this.model)}).done(this.recordsResponse).fail(this.failResponse);};Collection.prototype.fetch=function(params,options){var id,_this=this;if(params==null){params={};}
if(options==null){options={};}
if(id=params.id){delete params.id;return this.find(id,params).done(function(result){if(result.code==1000){return _this.model.refresh(result.data,options);}});}
else{return this.all(params).done(function(result){if(result.code==1000){return _this.model.refresh(result.data,options);}});}};Collection.prototype.recordsResponse=function(data,status,xhr){return this.model.trigger('ajaxSuccess',data,status,xhr);};Collection.prototype.failResponse=function(xhr,statusText,error){return this.model.trigger('ajaxError',xhr,statusText,error);};return Collection;})(Base);Singleton=(function(_super){__extends(Singleton,_super);function Singleton(record){this.record=record;this.failResponse=__bind(this.failResponse,this);this.recordResponse=__bind(this.recordResponse,this);this.model=this.record.constructor;}
Singleton.prototype.reload=function(params,options){return this.ajaxQueue(params,{type:'GET',url:Ajax.getURL(this.record)}).done(this.recordResponse(options)).fail(this.failResponse(options));};Singleton.prototype.create=function(params,options){return this.ajaxQueue(params,{type:'POST',data:JSON.stringify(this.record),url:Ajax.getURL(this.model)}).done(this.recordResponse(options)).fail(this.failResponse(options));};Singleton.prototype.update=function(params,options){return this.ajaxQueue(params,{type:'PUT',data:JSON.stringify(this.record),url:Ajax.getURL(this.record)}).done(this.recordResponse(options)).fail(this.failResponse(options));};Singleton.prototype.destroy=function(params,options){return this.ajaxQueue(params,{type:'DELETE',url:Ajax.getURL(this.record)}).done(this.recordResponse(options)).fail(this.failResponse(options));};Singleton.prototype.recordResponse=function(options){var _this=this;if(options==null){options={};}
return function(data,status,xhr){var _ref,_ref1;if(Spine.isBlank(data)){data=false;}
else{data=_this.model.fromJSON(data);}
Ajax.disable(function(){if(data){if(data.id&&_this.record.id!==data.id){_this.record.changeID(data.id);}
return _this.record.updateAttributes(data.attributes());}});_this.record.trigger('ajaxSuccess',data,status,xhr);if((_ref=options.success)!=null){_ref.apply(_this.record);}
return(_ref1=options.done)!=null?_ref1.apply(_this.record):void 0;};};Singleton.prototype.failResponse=function(options){var _this=this;if(options==null){options={};}
return function(xhr,statusText,error){var _ref,_ref1;_this.record.trigger('ajaxError',xhr,statusText,error);if((_ref=options.error)!=null){_ref.apply(_this.record);}
return(_ref1=options.fail)!=null?_ref1.apply(_this.record):void 0;};};return Singleton;})(Base);Model.host='';Include={ajax:function(){return new Singleton(this);},url:function(){var args,url;args=1<=arguments.length?__slice.call(arguments,0):[];url=Ajax.getURL(this.constructor);if(url.charAt(url.length-1)!=='/'){url+='/';}
url+=encodeURIComponent(this.id);args.unshift(url);return args.join('/');}};Extend={ajax:function(){return new Collection(this);},url:function(){var args;args=1<=arguments.length?__slice.call(arguments,0):[];args.unshift(this.className.toLowerCase()+'s');args.unshift(Model.host);return args.join('/');}};Model.Ajax={extended:function(){this.fetch(this.ajaxFetch);this.change(this.ajaxChange);this.extend(Extend);return this.include(Include);},ajaxFetch:function(){var _ref;return(_ref=this.ajax()).fetch.apply(_ref,arguments);},ajaxChange:function(record,type,options){if(options==null){options={};}
if(options.ajax===false){return;}
return record.ajax()[type](options.ajax,options);}};Model.Ajax.Methods={extended:function(){this.extend(Extend);return this.include(Include);}};Ajax.defaults=Base.prototype.defaults;Spine.Ajax=Ajax;if(typeof module!=="undefined"&&module!==null){module.exports=Ajax;}
return Spine;});D.regNs('core.util.dropdown',function(){return function(el,opts){opts=opts||{},attrs=['input','list','item','hoveCls'];for(var i=0;i<attrs.length;i++){if(!attrs[i]in opts){throw new Error(attrs[i]+' attr is not exist!');}}
var input=$(opts.input,el),list=$(opts.list,el);input.on('click',function(){list.toggle();return false;});list.on('click',opts.item,function(evt){var target=$(evt.currentTarget),val=target.attr('data-val');input.html(val);list.hide();evt.preventDefault();}).on('mouseenter',opts.item,function(evt){$(this).addClass(opts.hoveCls).siblings().removeClass(opts.hoveCls);});$(document.body).on('click',function(evt){var target=evt.currentTarget;if(list.is(':visible')&&!$.contains(list,target)){list.hide();}});}});D.regNs('comp.category.result',function(){var $spine=D.core.base.spine,$observer=D.core.util.observer,$ajax=D.core.base.ajax,$tmpl=D.core.util.easyTemplate,$dropdown=D.core.util.dropdown;var errorMsg={netError:'网络错误，请稍后重试',charset:"<div class='div_search_error'><span>只能输入英文内容！</span></div>"};var resultModel=$spine.Model.setup('result',['catePubId','categoryPath','categoryPathChinese']);resultModel.extend($spine.Model.Ajax);resultModel.url='/syi/searchPubName.do?isblank=true';var resultControl=$spine.Controller.create({init:function(){if(!this.input.prop('placeholder')){this.input.on('blur focus',$.proxy(this.fnFocus,this));}
var autoOpts={url:'/syi/searchAutomatic.do',appendTo:this.autoAppend,name:'search_input',delay:200,selectCls:'sac_over'}
this.autoComplete(this.input,autoOpts);$observer.subscribe('submit.autocomplete',$.proxy(this.fnDelegateSubmit,this));resultModel.bind('refresh',$.proxy(this.fnRender,this)).bind('ajaxSuccess',$.proxy(this.fnAjaxSuccess,this)).bind('ajaxError',$.proxy(this.fnAjaxError,this));$dropdown(this.langeSelect,{input:'.drop-down-value',list:'.chouse-down-box',item:'span[data-val]',hoveCls:'hover'});var $this=this;$observer.subscribe('change.langue',function(evt,param){$this.lang=param;$('[data-en]',$this.el).each(function(){var $this=$(this),attr='data-'+param,val=$this.attr(attr);$this.html(val).attr('title',val)});});},lang:'cn',autoComplete:function(el,opts){D.core.ui.autocomplete(el,opts);},events:{'submit form':'fnSubmit','click .search-sailtips-box li':'fnSelectResult','mouseenter .search-sailtips-box li':'fnHoverResult','mouseleave .search-sailtips-box li':'fnHoverResult','click .viewticps':'fnToggleBtn','click .chouse-down-box span':'fnChangeLange'},elements:{'.search-input':'input','.search-association':'autoAppend','form.search-model':'form','.search-sailtips-box':'searchList','.search-source':'searchResult','.show_search_input':'searchInput','.drop-down':'langeSelect','.search-tiperror':'error','.search-none':'searchNone'},fnAjaxSuccess:function(data,status){this.error.hide();if(status=='success'){if(data.code!=1000){alert(data.msg);}}else{alert(errorMsg.netError);}},fnAjaxError:function(data,status){this.error.show();this.searchResult.hide();},fnChangeLange:function(evt){var target=$(evt.currentTarget),param=target.attr('data-param');$observer.publish('change.langue',param);return false;},fnSelectResult:function(evt){var target=$(evt.currentTarget),param=target.attr('data-param');target.attr('data-select',1).siblings('[data-select]').removeAttr('data-select').removeClass('hover');$observer.publish('select.result',[param]);},fnHoverResult:function(evt){var target=$(evt.currentTarget),onCls='hover';switch(evt.type){case'mouseenter':target.addClass(onCls).siblings("."+onCls).not('[data-select]').removeClass(onCls);break;case'mouseleave':target.not('[data-select]').removeClass(onCls);break;}
return false;},fnRender:function(recodes,options){var searchList=this.searchList.empty();if(recodes&&recodes.length){var htmls=$tmpl(this.fnGetTmpl(),{rows:recodes,lang:this.lang}).toString();searchList.show().html(htmls);this.searchNone.empty();this.searchResult.show();}else{searchList.hide();this.searchNone.html('<div class="search-none">没有找到与"<b>'+this.input.val()+'</b>"相关的类目</div>');}
return false;},fnToggleBtn:function(evt){var target=$(evt.currentTarget);if(target.hasClass('viewshow')){target.removeClass('viewshow').html('收起<span class="darrow"></span>');this.searchList.removeClass('addheight');}else{target.addClass('viewshow').html('展开<span class="darrow"></span>');this.searchList.addClass('addheight');}
return false;},fnGetTmpl:function(){return'<#tpl data>\
      <ul>\
      <#list data.rows as row>\
       <li data-en="${row.categoryPath}" title="${data.lang == "cn"?row.categoryPathChinese:row.categoryPath}" data-param="catePubId=${row.catePubId}" data-cn="${row.categoryPathChinese}">\
        ${data.lang == "cn"?row.categoryPathChinese:row.categoryPath}\
       </li>\
      </#list>\
      </ul>\
     </#tpl>';},fnSubmit:function(evt){evt.preventDefault();$observer.publish('hide.autocomplete');var val=this.input.val(),val=$.trim(val).replace(/&/g,'&amp;');if(val.length){this.searchInput.html(val);resultModel.fetch({data:this.form.serialize(),type:'get'});}else{this.input.focus();}
return false;},fnDelegateSubmit:function(){this.form.trigger('submit');return false;},fnFocus:function(evt){var target=$(evt.currentTarget),val=$.trim(target.val()),placeholder=target.attr('placeholder');switch(evt.type){case'focus':if(val==placeholder){target.val('').removeClass('placeholder');}
break;case'blur':if(!val.length){target.val(placeholder).addClass('placeholder');}
break;}}});return resultControl;});D.regJob('pl.category.result',function(){var node=$('#search-box');if(node.length){new D.comp.category.result({el:node});}});D.regNs('comp.category.history',function(){var $spine=D.core.base.spine,$observer=D.core.util.observer,$tmpl=D.core.util.easyTemplate,$dropdown=D.core.util.dropdown;var historyModel=$spine.Model.setup('history',['catePubId','categoryPath','categoryPathChinese']);historyModel.extend($spine.Model.Ajax);historyModel.url='/syi/recentCategory.do';var historyControl=$spine.Controller.create({init:function(){historyModel.bind('refresh',$.proxy(this.fnRender,this));historyModel.fetch();$dropdown(this.droplist,{input:'.drop-down-value',list:'.chouse-down-box',item:'span',hoveCls:'hover'});var $this=this;$observer.subscribe('change.langue',function(evt,param){$this.lang=param;$('[data-en]',$this.el).each(function(){var $this=$(this),val=$this.attr('data-'+param);$this.html(val).attr('title',val).attr('data-val',val)});});},lang:'cn',events:{'click .chouse-down-box span':'fnClickItem'},elements:{'.chouse-down-box':'dropdown','.drop-down':'droplist'},fnClickItem:function(evt){var target=$(evt.currentTarget),param=target.attr('data-param');$observer.publish('select.result',[param]);return false;},fnRender:function(records){var dropdown=this.dropdown.empty();if(records&&records.length){var htmls=$tmpl(this.fnGetTmpl(),{rows:records,lang:this.lang}).toString();dropdown.html(htmls);}},fnGetTmpl:function(){return'<#tpl data>\
      <#list data.rows as row>\
       <span title="${data.lang=="en"?row.categoryPathChinese:row.categoryPathChinese}" data-en="${row.categoryPath}" data-val="${row.categoryPathChinese}" data-cn="${row.categoryPathChinese}" data-param="isblank=true&catePubId=${row.catePubId}">\
       ${data.lang=="en"?row.categoryPathChinese:row.categoryPathChinese}</span>\
      </#list>\
     </#tpl>';}});return historyControl;});D.regJob('pl.category.history',function(){var node=$('#search-history');if(node.length){new D.comp.category.history({el:node});}});D.regNs('core.util.browser',function(D,$){var matched,browser;var uaMatch=function(ua){ua=ua.toLowerCase();var match=/(chrome)[ \/]([\w.]+)/.exec(ua)||/(webkit)[ \/]([\w.]+)/.exec(ua)||/(opera)(?:.*version|)[ \/]([\w.]+)/.exec(ua)||/(msie) ([\w.]+)/.exec(ua)||ua.indexOf("compatible")<0&&/(mozilla)(?:.*? rv:([\w.]+)|)/.exec(ua)||[];return{browser:match[1]||"",version:match[2]||"0"};};matched=uaMatch(navigator.userAgent);browser={};if(matched.browser){browser[matched.browser]=true;browser.version=matched.version;}
if(browser.chrome){browser.webkit=true;}
else
if(browser.webkit){browser.safari=true;}
return browser;});D.regNs('core.ui.dialog',function($,D){var TMPL='<#tpl data>\
     <table class="noshade-pop-table <#if (data.className)>${data.className}</#if> ">\
               <tbody>\
        <tr>\
                     <td class="t-lt"></td>\
                     <td class="t-mid"></td>\
                     <td class="t-ri"></td>\
                 </tr>\
                <tr>\
                    <td class="m-lt"></td>\
                    <td class="m-mid">\
                        <div class="mid-warp">\
                            <div class="noshade-pop-content">\
                                <div class="noshade-pop-inner">\
                                    <div class="noshade-pop-title">\
                                        <span>${data.title}</span>\
                                    </div>\
                                    <span id="pop_inner" class="pop_inner"></span>\
                                </div>\
                                <div class="noshade-pop-bot"></div>\
                                <a  href="javascript:;" class="noshade-pop-close close"></a>\
                            </div>\
                        </div>\
                    </td>\
                    <td class="m-ri"></td>\
                </tr>\
                <tr>\
                    <td class="b-lt"></td>\
                    <td class="b-mid"></td>\
                    <td class="b-ri"></td>\
                </tr>\
            </tbody>\
     </table>\
    </#tpl>';return function(opts){var _opts={draggable:false,style:{width:'485px',height:'auto'},attrs:{'class':'dialog',title:'提示','className':'dialog'},cssText:'position:fixed;*position:absolute;left:0;top:0;z-index:1000;',autoOpen:true,modelClass:'modalOverlay',html:'',appendTo:document.body,model:true};if(opts){$.extend(_opts,opts);}
var $tmpl=D.core.util.easyTemplate,$browser=D.core.util.browser,$observer=D.core.util.observer,dia=$($.trim($tmpl(TMPL,_opts.attrs).toString())).appendTo(_opts.appendTo),supportFixed=!($browser.msie&&$browser.version==6),mask,inner=$('.pop_inner',dia);if(_opts.model){mask=$('<div id="'+_opts.modelClass+'" class="'+_opts.modelClass+'" style="opacity: 0.5; height: 100%; width: 100%; position: fixed; left: 0px; top: 0px; z-index: 999;"></div>').hide().appendTo(document.body);}
inner.html(opts.html);if(_opts.cssText){dia.css('cssText',_opts.cssText);}
dia.css(_opts.style).on('click','.close',function(evt){dia.trigger('close.dialog');dia.off().remove();_opts.model&&mask.remove();}).on('close.dialog',function(){$(window).off('.dialog');}).on('open.dialog',function(evt){_opts.model&&mask.show();dia.show().trigger('middle.dialog');$(window).on('resize.dialog scroll.dialog',function(){dia.trigger('middle.dialog');});}).on('middle.dialog',function(){dia.css({left:($(window).width()-dia.width())/2+(!supportFixed?$(this).scrollTop():0),top:($(window).height()-dia.height())/2+(!supportFixed?$(this).scrollLeft():0)});});if(_opts.autoOpen){dia.trigger('open.dialog');}
return dia;};});D.regNs('comp.category.index',function($,D){var $spine=D.core.base.spine,$dia=D.core.ui.dialog,$observer=D.core.util.observer,$ajax=D.core.base.ajax,$tmpl=D.core.util.easyTemplate,jqXHR=null;var categoryModel=$spine.Model.setup('category',['catePubId','categoryPath','categoryPathChinese']);categoryModel.extend($.extend({cacheFecth:function(param,options){var $this=this,options=options||{clear:true},param=param||{},key=$.type(param)=='object'?JSON.stringify(param):param;$this.url='/syi/categorybyid.do?isblank=true'
options.key=key;if($this.cache[key]){$this.refresh($this.cache[key],options);}else{jqXHR&&jqXHR.abort&&jqXHR.abort();jqXHR=$this.ajax().all({data:param,processData:true,dataType:'json',cache:false}).done(function(result){if(result.code==1000){if(!result.data){result.data=[];}else{$this.cache[key]=result.data;}
$this.refresh(result.data,options)}});}},refresh:function(values,options){var record,records,_i,_len;if(options==null){options={};}
if(options.clear){this.records={};this.crecords={};}
records=this.fromJSON(values);if(!$.isArray(records)){records=[records];}
for(_i=0,_len=records.length;_i<_len;_i++){record=records[_i];record.id||(record.id=record.cid);this.records[record.id]=record;this.crecords[record.cid]=record;}
this.trigger('refresh',this.cloneArray(records),options);return this;},cacheFetchAll:function(param,options){var $this=this,key=$.type(param)=='object'?JSON.stringify(param):param;$this.url='/syi/selectedCategories.do?isblank=true';if($this.cache[key]){$this.trigger('refreshAll',this.cache[key]);}else{jqXHR&&jqXHR.abort&&jqXHR.abort();jqXHR=$this.ajax().all({data:param,processData:true,dataType:'json',cache:false}).done(function(result){if(result.code==1000){if(!result.data){result.data=[];}else{$this.cache[key]=result.data;}
$this.trigger('refreshAll',result.data);}});}},cache:{}},$spine.Model.Ajax));var errorMsg={netError:'网络错误，请稍后重试',punish:'抱歉，由于您的帐户受到“限制类目经营”处罚，此类目不能上传新产品。处罚到期后可申请解除，具体请您查看站内信通知。',author:"此类目是限制级类目，您没有权限选择此类目!<a href='http://help.dhgate.com/dhgate/sellerhelpcn.php?catid=0201&artid=A77201D0866CBE90E04010AC0C64763E' target='_blank'>详情</a>",detail:"<a href='http://help.dhgate.com/dhgate/sellerhelpcn.php?catid=0201&artid=A77201D0866CBE90E04010AC0C64763E' target='_blank'>详情</a>",loading:"<div class='box1 clearfix'><div class='boxcenter clearfix'><p class='pop-button'><img src='http://www.dhresource.com/seller/images/index/loading.gif'/><span>正在载入草稿……</span></p></div></div>",nextLeave:'<span class="color4">（请选择下级类目）</span>'};var $hid=$CONF.hid||{},$catePunishSet=$CONF.catePunishSet||[];var categoryControl=$spine.Controller.create({init:function(){var $this=this;categoryModel.bind('refresh',$.proxy(this.fnRenderList,this));categoryModel.bind('refreshAll',$.proxy(this.fnRenderAll,this));categoryModel.bind('ajaxError',$.proxy(this.fnAjaxError,this));$observer.subscribe('select.result',function(evt,params){categoryModel.cacheFetchAll(params);});var $this=this;$observer.subscribe('change.langue',function(evt,param){$this.lang=param;$('[data-en]',$this.el).each(function(){var $this=$(this),attr='data-'+param,val=$this.attr(attr),limit=$this.attr('data-admittancedto');$this.attr('title',val);if(!limit){$this.html(val);}else{$this.html('<span class="limited"><span> '+val+'</span></span>');}});});if($CONF['draft']){this.fnLoadDraft();}
if($hid['catePubId']){var params='catePubId='+$hid['catePubId'];categoryModel.cacheFetchAll(params);this.showChargeTip(params);}},lang:'cn',catalogs:[],events:{'click .categoryselectlistbox li':'fnClickItem','checkInfo .categoryselectlistbox li':'fnCheckItem','click .submit_button':'fnSubmitForm','click #div_catagory0 li':'fnShowCharges'},elements:{'.show_category_path':'path','.submit_button .submit-syi':'submitbtn','.categoryselectlist':'append','.show_remark':'showRemark','.selected-category-tip':'remarkWrap','.chousetips':'message'},fnAjaxError:function(){},fnShowCharges:function(evt){var target=$(evt.currentTarget),param=target.attr('data-param');this.showChargeTip.call(this,param);},showChargeTip:function(param){return;var url='/syi/commissionCate.do',result,el=$('#yongjin'),wrap=$('#div_show_yongjin');;if(!this.chargeCache){this.chargeCache={};}
var showTips=function(result){if(result.code==1000){el.html(result.data.value);wrap.show();}else{wrap.hide();}}
var caches=this.chargeCache;if(result=caches[param]){showTips(result);return;}
if(this.xhr&&this.xhr.abort){this.xhr.abort();}
this.xhr=$.get(url,param,function(result){if(result.code==1000){caches[param]=result;}},'json');},fnLoadDraft:function(){var diaTmpl=$tmpl($('#syidraft').html(),$CONF['draft']).toString();var dia=$dia({html:diaTmpl});dia.on('click','.pubproduct',function(){$(".pop_inner",dia).html(errorMsg.loading);location.href="/syi/edit.do?isdraftbox=1";return false;});},fnCheckItem:function(evt){var target=$(evt.currentTarget),param=target.attr('data-param'),catePubId=param.replace(/^catePubId=/g,''),msg=target.attr('data-message'),limit=target.attr('data-admittanceDto'),admittanceid=target.attr('data-admittanceid'),onCls='current',leaf=target.attr('data-leaf'),en=target.attr('data-en'),cn=target.attr('data-cn'),text=this.lang=='cn'?(cn+'('+en+')'):(en+'('+cn+')'),list=target.closest('.categoryselectlist'),remark=target.attr('data-remark'),index=list.index(),enableBtn=(leaf==1&&!limit)?true:false;if(!limit){limit=$.inArray(catePubId,$catePunishSet)!=-1?true:false;}
target.addClass(onCls).siblings('.'+onCls).removeClass(onCls);if(remark&&remark.length){this.showRemark.html(remark);this.remarkWrap.show();}else{this.remarkWrap.hide();}
if(limit){msg=msg||(errorMsg.punish+errorMsg.detail);if(admittanceid=="0"||admittanceid==1){msg=errorMsg.author;}
this.message.html(msg).show();}else{this.message.hide();}
this.catalogs.length=index;this.catalogs.push('<b>'+text+'</b>');var pathName=this.catalogs.join('<span>&gt;</span>');if(leaf!=1){pathName+=errorMsg.nextLeave;}else{$hid['inp_catepubid']=(param||'').split('=')[1];}
this.path.html(pathName);this.fuEnableBtn(enableBtn);},fnClickItem:function(evt){var target=$(evt.currentTarget),leaf=target.attr('data-leaf'),list=target.closest('.categoryselectlist');var next=list.nextAll('.categoryselectlist').empty().first();if(leaf!=1){var param=target.attr('data-param');categoryModel.cacheFecth(param,{append:next,clear:true});}
target.trigger('checkInfo');return false;},fuEnableBtn:function(bl){if(bl){this.submitbtn.removeClass('initialstate');}else{this.submitbtn.addClass('initialstate');}
return false;},fnRenderAll:function(recordes){var $this=this,append=null;this.append.empty();$.each(recordes,function(key,row){append=$($this.append[key]),options={append:append};$this.fnRenderList(row,options);$('li.current',append).trigger('checkInfo');});},fnRenderList:function(recordes,params){var append=params.append,htmls='';if(recordes&&recordes.length){append.addClass('addscroll');htmls=$tmpl(this.fnGetTmpl(),{rows:recordes,lang:this.lang}).toString();}else{append.removeClass('addscroll');}
append.html(htmls).show();},fnGetTmpl:function(){return'<#tpl data>\
       <ul>\
        <#list data.rows as row>\
         <li title="${data.lang == "cn" ? row.pubNameCn : row.pubName}"  <#if (row.remark)> data-remark="${row.remark}"</#if>  <#if (row.admittanceDto)> data-message="${row.admittanceDto.message}" data-admittanceDto="1" data-admittanceid="${row.admittanceDto.admittanceid}" </#if>  <#if (row.selected)>class="current"</#if>  data-leaf="${row.leaf}" data-valid="${row.valid}" data-param="catePubId=${row.catePubId}" data-en="${row.pubName}" data-cn="${row.pubNameCn}">\
         <#if (row.admittanceDto)>\
         <span class="limited"><span> ${data.lang == "cn" ? row.pubNameCn : row.pubName}</span></span>\
         <#else>\
         ${data.lang == "cn" ? row.pubNameCn : row.pubName}\
         </#if>\
         </li>\
        </#list>\
       </ul>\
      </#tpl>';},fnSubmitForm:function(evt){var target=$(evt.currentTarget),span=$('span.submit-syi',target),flagCls='initialstate';if(span.hasClass(flagCls)){return false;}else{$.map($hid,function(val,key){if(val==null){delete $hid[key];}});var url='/syi/edit.do?'+$.param($CONF.hid);window.location.href=url;return false;}}});return categoryControl;});D.regJob('pl.category.index',function(){var node=$('#greay-cat-box');if(node.length){new D.comp.category.index({el:node});}});D.startJob();